import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../globals.css'
import { getServerSession } from "next-auth";
import Provider from "../(context)/client-provider";
import { redirect } from "next/navigation";
import { options } from "../api/auth/[...nextauth]/options";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function asyncRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options);
  if (!session?.idToken) {
    redirect("/signin")
  }
  return (
    <html lang="en">
      <Provider session={session}>
        <body className={inter.className}>{children}</body>
      </Provider>
    </html>
  );
}
